kind: Service
apiVersion: v1
metadata:
  name: api
  namespace: mock-api
  annotations:
    beta.cloud.google.com/backend-config: '{"default": "api-backend"}'
spec:
  type: NodePort
  selector:
    name: api
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
